//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BHYT
    {
        public string ID { get; set; }
        public string ID_BAOHIEM { get; set; }
        public string MANV { get; set; }
        public string MABH { get; set; }
        public string NOIDANGKY { get; set; }
        public string GTSD { get; set; }
        public string NOICAP { get; set; }
        public string MAVUNG { get; set; }
    
        public virtual BAOHIEM BAOHIEM { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
