//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        public string MAHD { get; set; }
        public string MANV { get; set; }
        public string LOAIHD { get; set; }
        public Nullable<System.DateTime> NGAYKIHD { get; set; }
        public Nullable<System.DateTime> NGAYKTHD { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
