//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.BHXH = new HashSet<BHXH>();
            this.BHYT = new HashSet<BHYT>();
            this.HOPDONG = new HashSet<HOPDONG>();
            this.PHIEUNGHIPHEP = new HashSet<PHIEUNGHIPHEP>();
            this.PHIEULUONG = new HashSet<PHIEULUONG>();
            this.TAIKHOANNGUOIDUNG = new HashSet<TAIKHOANNGUOIDUNG>();
        }
            
        
        public string MANV { get; set; }
        public string CCCD { get; set; }
        public string HOTEN { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string NOISINH { get; set; }
        public string SDT { get; set; }
        public string MADT { get; set; }
        public string MATG { get; set; }
        public string MAQT { get; set; }
        public string MACV { get; set; }
        public string MAPB { get; set; }
        public string MATD { get; set; }
        public string TENDANTOC { get; set; }
        public string TENTONGIAO { get; set; }
        public string TENQUOCTICH { get; set; }
        public string TENTRINHDO { get; set; }
        public string TENPHONGBAN { get; set; }
        public string TENCHUCVU { get; set; }
        public string GHICHU { get; set; }
        [NotMapped]
        public List<DANTOC> listdantoc { get; set; } = new List<DANTOC>();
        public List<QUOCTICH> listquoctich { get; set; } = new List<QUOCTICH>();
        public List<TONGIAO> listtongiao { get; set; } = new List<TONGIAO>();
        public List<CHUCVU> listchucvu { get; set; } = new List<CHUCVU>();
        public List<PHONGBAN> listphongban { get; set; } = new List<PHONGBAN>();
        public List<TRINHDO> listtrinhdo { get; set; } = new List<TRINHDO>();
        public List<NHANVIEN> listNV { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BHXH> BHXH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BHYT> BHYT { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual DANTOC DANTOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONG> HOPDONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUNGHIPHEP> PHIEUNGHIPHEP { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        public virtual QUOCTICH QUOCTICH { get; set; }
        public virtual TONGIAO TONGIAO { get; set; }
        public virtual TRINHDO TRINHDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEULUONG> PHIEULUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOANNGUOIDUNG> TAIKHOANNGUOIDUNG { get; set; }
    }
}
