//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNSuEntities : DbContext
    {
        public QLNSuEntities()
            : base("name=QLNSuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAOHIEM> BAOHIEM { get; set; }
        public virtual DbSet<BHXH> BHXH { get; set; }
        public virtual DbSet<BHYT> BHYT { get; set; }
        public virtual DbSet<CHUCVU> CHUCVU { get; set; }
        public virtual DbSet<DANTOC> DANTOC { get; set; }
        public virtual DbSet<HOPDONG> HOPDONG { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<PHIEULUONG> PHIEULUONG { get; set; }
        public virtual DbSet<PHIEUNGHIPHEP> PHIEUNGHIPHEP { get; set; }
        public virtual DbSet<PHONGBAN> PHONGBAN { get; set; }
        public virtual DbSet<QUOCTICH> QUOCTICH { get; set; }
        public virtual DbSet<TAIKHOANADMIN> TAIKHOANADMIN { get; set; }
        public virtual DbSet<TAIKHOANNGUOIDUNG> TAIKHOANNGUOIDUNG { get; set; }
        public virtual DbSet<TONGIAO> TONGIAO { get; set; }
        public virtual DbSet<TRINHDO> TRINHDO { get; set; }
        public virtual DbSet<VAITRO> VAITRO { get; set; }
    }
}
